name: memorandom
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  gradient_app_bar: ^0.1.3
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  carousel_slider: ^1.4.1
  http: ^0.12.1
  step_progress_indicator: ^0.2.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
